# This workflow will do a clean installation of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test and publish

on:
  workflow_dispatch:
    inputs:
      run-tests:
        description: "Manual deployer for prod"
        required: false
        default: true
        type: boolean
  release:
    types:
      - released

jobs:
  quality:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        os: [ubuntu-latest, windows-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        # Jest 30 requires Node.js 18.x or higher

    steps:
      - name: Checkout Frontend Git Repo
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run:  |
          npm install -g pnpm@8.15.7
          pnpm install

      - name: Run tests
        run: pnpm test

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' }}
    needs: [quality]
    steps:
      - name: Checkout Frontend Git Repo
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org

      - name: Install Packages
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build npm package
        run: pnpm build-lib

      - name: Publish
        run: npm publish --access public
        working-directory: lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
